services:
  mq:
    image: rabbitmq:management

  cache:
    image: redis:latest

  db:
    image: postgres:latest

  api:
    image: ${DOCKER_REGISTRY:+${DOCKER_REGISTRY}/}${OWNER:+${OWNER}/}netflex-api:latest
    build:
      context: .
      dockerfile: Presentation/Netflex.WebAPI/Dockerfile

volumes:
  db-data: