services:
    mq:
      container_name: netflex-mq-prod
      hostname: netflex-mq
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"

    cache:
      container_name: netflex-cache-prod
      restart: always
      ports:
        - "6379:6379"

    db:
      container_name: netflex-db-prod
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=netflex
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - netflex-data:/var/lib/postgresql/data/

    api:
      container_name: netflex-api-prod
      environment: 
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - GoogleSettings__CredentialsFile=/app/secrets/google.credentials.json
      env_file:
        - .env
      depends_on:
        - db
        - cache
      ports:
        - "6000:8080"
      volumes:
        - ~/.aspnet/https:/https:ro
        - ./google.credentials.json:/app/secrets/google.credentials.json:ro