services:
    mq:
      container_name: netflex-mq-prod
      hostname: netflex-mq
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"

    cache:
      container_name: netflex-cache-prod
      restart: always
      ports:
        - "6379:6379"

    db:
      container_name: netflex-db-prod
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=netflex
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - db-data:/var/lib/postgresql/data/

    api:
      container_name: netflex-api-prod
      environment: 
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
      env_file:
        - .env
      depends_on:
        - db
        - cache
      ports:
        - "6000:8080"
      volumes:
        - ~/.aspnet/https:/https:ro

    watchtower:
      container_name: watchtower
      environment:
        - WATCHTOWER_CLEANUP=true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: --interval 30 netflex-api-prod