services:
  cache:
    image: redis:latest

  db:
    image: postgres:latest

  webapi:
    image: ${DOCKER_REGISTRY-}netflex-api
    build:
      context: .
      dockerfile: Presentation/Netflex.WebAPI/Dockerfile

volumes:
  db-data: