services:
  mq:
    image: rabbitmq:management

  cache:
    image: redis:latest

  db:
    image: postgres:latest

  api:
    image: ghcr.io/ngoxuanbac/netflex-api:latest
    build:
      context: .
      dockerfile: Presentation/Netflex.WebAPI/Dockerfile

  watchtower:
    image: containrrr/watchtower:latest

volumes:
  db-data: