services:
    cache:
      container_name: netflex-cache-prod
      restart: always
      ports:
        - "6379:6379"

    db:
      container_name: netflex-db-prod
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=netflex
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - db-data:/var/lib/postgresql/data/

    webapi:
      container_name: netflex-api-prod
      environment: 
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ConnectionStrings__Cache=cache:6379
        - ConnectionStrings__Database=Server=db;Port=5432;Database=netflex;User Id=postgres;Password=postgres;Include Error Detail=true
      env_file:
        - .env
      depends_on:
        - db
        - cache
      ports:
        - "6000:8080"
      volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        - ~/.aspnet/https:/https:ro